name: Build artifacts

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
        description: GITHUB_TOKEN to access the repository

env:
  REGISTRY: ghcr.io

jobs:
  next_semantic_version:
    uses: ./.github/workflows/next-semantic-version.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_image:
    needs:
      - next_semantic_version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Go version
        id: go_version
        shell: bash
        run: |
          echo "GO_VERSION=$(sed -En 's/^go[[:space:]]+([[:digit:].]+)$/\1/p' go.mod)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set REPOSITORY (lowercase)
        run: echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args:
            GO_VERSION=${{ steps.go_version.outputs.GO_VERSION }}
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:v${{ needs.next_semantic_version.outputs.next_release_version }}
