name: Main CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    needs:
      - test
    uses: ./.github/workflows/build.yaml
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs:
      - test
      - build
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub release
      issues: write # Comment on issues
      pull-requests: write # Comment on PR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Release
        run: npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
