name: Next Semantic Version

on:
  workflow_call:
    outputs:
      next_release_version:
        description: The next semantic release version
        value: ${{ jobs.next_version.outputs.next_semantic_version }}

jobs:
  next_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      next_semantic_version: ${{ steps.semantic.outputs.NEXT_SEMANTIC_RELEASE_VERSION }}
    steps:
      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Get next semantic version
        id: semantic
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NEXT_SEMANTIC_RELEASE_VERSION=$(npx semantic-release --dry-run --no-ci --branches ${{ steps.branch.outputs.BRANCH }} | grep 'next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "NEXT_SEMANTIC_RELEASE_VERSION=${NEXT_SEMANTIC_RELEASE_VERSION}" >> $GITHUB_OUTPUT
