name: PR CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  check_docker_image:
    name: Check Docker image version
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current docker image version
        id: current_version
        run: |
          echo "DOCKER_IMAGE_VERSION=$(cat action.yaml | grep "docker://ghcr.io" | sed -E 's/.*:v([0-9]*.[0-9]*.[0-9]*)$/\1/')" >> "$GITHUB_OUTPUT"

      - name: Compare docker image with next version
        uses: actions/github-script@v7
        with:
          script: |
            if ("${{ needs.get-next-version.outputs.new-release-version }}" !== "${{ steps.current_version.outputs.DOCKER_IMAGE_VERSION }}") {
              core.setFailed("The action.yaml's Docker image is pointing at ${{ steps.current_version.outputs.DOCKER_IMAGE_VERSION }} but it should point at the next semantic version ${{ needs.get-next-version.outputs.new-release-version }}")
            }

