name: PR CI

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml

  next_semantic_version:
    uses: ./.github/workflows/next-semantic-version.yaml

  check_docker_image:
    needs:
      - next_semantic_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current docker image version
        id: current_version
        run: echo "DOCKER_IMAGE_VERSION=$(s/docker:\/\/ghcr.io\/landazuripaul\/time-window-validator:v[0-9]*.[0-9]*.[0-9]*/\1/g')" >> "$GITHUB_OUTPUT"

      - name: Compare docker image with next version
        uses: actions/github-script@v7
        with:
          script: |
            if ("${{ needs.next_semantic_version.outputs.next_release_version }}" !== "${{ steps.current_version.outputs.DOCKER_IMAGE_VERSION }}") {
              core.setFailed("The action.yaml's Docker image is pointing at ${{ steps.current_version.outputs.DOCKER_IMAGE_VERSION }} but it should point at the next semantic version ${{ needs.next_semantic_version.outputs.next_release_version }}")
            }

