name: Test the Time Window action

on:
  pull_request:
  push:

jobs:
  test_cli:
    name: Test the CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
         go-version: 1.23.2

      - name: Install dependencies
        run: go mod download

      - name: Test with the Go CLI
        run: go test -v ./...

  test_action:
    name: Test the GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test  Docker action
        id: time_window
        uses: ./
        with:
          allowed: |
            - name: Office hours
              cronExpression: "0 9 * * 1-5"
              duration: 8h
          blocked: |
            - name: Christmas holidays
              cronExpression: "0 0 24 12 *"
              duration: 96h

      - name: Print results
        shell: bash
        run: |
          echo "error: ${{ steps.time_window.outputs.error }}"
          echo "is_valid: ${{ steps.time_window.outputs.is_valid }}"
          echo "message: ${{ steps.time_window.outputs.message }}"
          echo "timestamp: ${{ steps.time_window.outputs.timestamp }}"
          echo `result: ${{ steps.time_window.outputs.result }}`
          echo "json_error: ${{ fromJSON(steps.time_window.outputs.result).error }}"
          echo "json_isValid: ${{ fromJSON(steps.time_window.outputs.result).isValid }}"
          echo "json_message: ${{ fromJSON(steps.time_window.outputs.result).message }}"
          echo "json_timestamp: ${{ fromJSON(steps.time_window.outputs.result).timestamp }}"
